# Session

In [2]:
import sys
import os
from pathlib import Path

from snowflake.core import Root

from snowflake.snowpark.session import Session


current_file_path = Path().resolve()
sys.path.insert(0, str(current_file_path.parent))
sys.path.insert(0, str(current_file_path.parent / "src"))


# Custom python file import
# Import statement after adding parent file path to recognize src python files
from src.support_agent.config import get_settings
from src.support_agent.snowflake_client import create_snowpark_session


# Getting .env config and init snowflake session
settings = get_settings()
session = create_snowpark_session(settings)

# Eval Dataset Pipeline


## Phase 0: Setup & Validation (Before Everything)

```
ENVIRONMENT
x Snowflake free account accessible
x Raw tickets loaded in Snowflake table
x Confirm table structure (ticket_id, subject, body, answer, language, queue, priority, ...)
x Confirm available Snowflake Cortex LLM models (mistral-large, llama, ...)
```

```
DATA EXPLORATION (do this first, know your data)
x Count total tickets → confirm ~28,500
x Count tickets per language
x Count tickets per queue/category
x Count tickets per priority
x Check for NULL values in body / answer / subject
x Check average length of body and answer
x Spot check 20-30 tickets manually → understand the data
x Cleaned dataset by removing unwanted data : (<50 char length on answer and body), remove cols (subject, tags)
```

---

In [9]:
query = """ SELECT * FROM PROJECT_DB.RAW.SUPPORT_TICKETS; """
df = session.sql(query).to_pandas().rename(columns=lambda s: s.lower())

In [ ]:
summary_stats = {
    'total_tickets': len(df),
    'tickets_per_language': df['LANGUAGE'].value_counts().to_dict(),
    'tickets_per_queue': df['QUEUE'].value_counts().to_dict(),
    'tickets_per_priority': df['PRIORITY'].value_counts().to_dict(),
    'null_values': dict(df.isna().sum().items()),
    'length_statistics': {
        'BODY': {
            'mean': df['BODY'].dropna().str.len().mean(),
            'median': df['BODY'].dropna().str.len().median(),
            'min': df['BODY'].dropna().str.len().min(),
            'max': df['BODY'].dropna().str.len().max()
        },
        'ANSWER': {
            'mean': df['ANSWER'].dropna().str.len().mean(),
            'median': df['ANSWER'].dropna().str.len().median(),
            'min': df['ANSWER'].dropna().str.len().min(),
            'max': df['ANSWER'].dropna().str.len().max()
        }
    }
}

In [44]:
cols = [col for col in df.columns[1:] if "tag" not in col]

In [ ]:
df_clean = df.loc[:, cols].copy()

In [48]:
df_clean = df_clean[df_clean['body'].str.len() >= 50]
df_clean = df_clean[df_clean['answer'].str.len() >= 50]

df_clean = df_clean.drop_duplicates(subset=['body', 'answer'])

final_stats = {
    'original_tickets': len(df),
    'cleaned_tickets': len(df_clean),
    'removed_tickets': len(df) - len(df_clean),
    'removal_percentage': ((len(df) - len(df_clean)) / len(df)) * 100,
    'tickets_per_language_cleaned': df_clean['language'].value_counts().to_dict(),
    'tickets_per_queue_cleaned': df_clean['queue'].value_counts().to_dict(),
    'tickets_per_priority_cleaned': df_clean['priority'].value_counts().to_dict(),
    'length_statistics_cleaned': {
        'body': {
            'mean': df_clean['body'].str.len().mean(),
            'median': df_clean['body'].str.len().median(),
            'min': df_clean['body'].str.len().min(),
            'max': df_clean['body'].str.len().max()
        },
        'answer': {
            'mean': df_clean['answer'].str.len().mean(),
            'median': df_clean['answer'].str.len().median(),
            'min': df_clean['answer'].str.len().min(),
            'max': df_clean['answer'].str.len().max()
        }
    }
}

In [73]:
# print(final_stats)

In [72]:
# min_threshold = 50
# max_threshold = 100

# low_body_tickets = df[(df['body'].str.len() >= min_threshold) & (df['body'].str.len() < max_threshold)].copy()
# low_answer_tickets = df[(df['answer'].str.len() >= min_threshold) & (df['answer'].str.len() < max_threshold)].copy()

# print("="*80)
# print(f"BODY TICKETS ({min_threshold}-{max_threshold} chars) - Total: {len(low_body_tickets)}")
# print("="*80)
# for idx, row in low_body_tickets.head(20).iterrows():
#     print(f"\nTicket #{idx}")
#     print(f"Language: {row['language']} | Queue: {row['queue']} | Priority: {row['priority']}")
#     print(f"Body ({len(row['body'])} chars): '{row['body']}'")
#     print(f"Answer: '{row['answer'][:100]}...'")
#     print("-"*80)

# print("\n\n")
# print("="*80)
# print(f"ANSWER TICKETS ({min_threshold}-{max_threshold} chars) - Total: {len(low_answer_tickets)}")
# print("="*80)
# for idx, row in low_answer_tickets.head(20).iterrows():
#     print(f"\nTicket #{idx}")
#     print(f"Language: {row['language']} | Queue: {row['queue']} | Priority: {row['priority']}")
#     print(f"Body: '{row['body'][:100]}...'")
#     print(f"Answer ({len(row['answer'])} chars): '{row['answer']}'")
#     print("-"*80)

# summary = {
#     'threshold_range': f'{min_threshold}-{max_threshold}',
#     'body_in_range_count': len(low_body_tickets),
#     'answer_in_range_count': len(low_answer_tickets),
#     'both_in_range_count': len(df[(df['body'].str.len() >= min_threshold) & (df['body'].str.len() < max_threshold) & 
#                                    (df['answer'].str.len() >= min_threshold) & (df['answer'].str.len() < max_threshold)])
# }

In [74]:
from snowflake.snowpark import Session
from snowflake.snowpark.functions import col

session.sql("CREATE SCHEMA IF NOT EXISTS PROJECT_DB.CURATED").collect()

df_clean_snowpark = session.create_dataframe(df_clean)

df_clean_snowpark.write.mode("overwrite").save_as_table("PROJECT_DB.CURATED.TICKETS_CLEANED")

/Users/sushiatomique/Documents/M2/TAL/.venv/lib/python3.11/site-packages/snowflake/snowpark/session.py:2618: UserWarning: Pandas Dataframe has non-standard index of type <class 'pandas.core.indexes.base.Index'> which will not be written. Consider changing the index to pd.RangeIndex(start=0,...,step=1) or call reset_index() to keep index as column(s)
  success, _, _, ci_output = write_pandas(

In [77]:

verify_query = """
SELECT *
FROM PROJECT_DB.CURATED.TICKETS_CLEANED
LIMIT 5;
"""

In [78]:

verification = session.sql(verify_query).to_pandas()

In [79]:
verification.head(2)

,body,answer,type,queue,priority,language,version
0,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51
1,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51

Some tips to improve this step : 
- Make a subject classifier
- Fill tags based on stratified samples (language * priority * queue) => UMAP + clustering on each combination then fill


## Phase 1: Resolution Classifier

```
PROMPT DESIGN
x Write classification prompt (RESOLUTION / CLARIFICATION / ESCALATION / PARTIAL)
x Test prompt manually on 5 tickets in Snowflake UI
x Adjust prompt if output is not clean (extra words, wrong format, ...)
```

```
VALIDATION BEFORE FULL RUN
x Manually label 20-30 diverse tickets yourself
x Run classifier on same 20-30 tickets
x If correct answer < 80 : rewrote the prompt
```

```
FULL RUN
x Run classifier on all 28,500 tickets
x Store result in new column answer_type
x Count per category (RESOLUTION / CLARIFICATION / ESCALATION / PARTIAL)
x Spot check 10-15 results manually to sanity check
x Decision: is count of RESOLUTION tickets sufficient? (need >> 1000)
x If not enough → decide if PARTIAL tickets should be included
```

---

Improvement possibility : 
- Rewrite classifier prompt
- Make a ML/Transformer based classifier
- use Snowflake builtin method ai_classify
- Check in a UI more samples to evaluate classification 
- Get some german people/translate it

In [50]:
df_clean.shape

(27733, 7)

In [52]:
df_clean.columns

Index(['body', 'answer', 'type', 'queue', 'priority', 'language', 'version'], dtype='object')

In [61]:
def classify_ticket_cortex(body, answer, model='claude-3-5-sonnet'):
    prompt = f"""You are a support ticket classifier. Analyze the support ticket body and answer, then classify the answer into ONE of these categories:

    - RESOLUTION: The answer completely resolves the customer's issue with a clear solution
    - CLARIFICATION: The answer asks for more information or clarification from the customer
    - ESCALATION: The answer indicates the issue is being escalated to another team or specialist
    - PARTIAL: The answer provides some help but doesn't fully resolve the issue, or provides a workaround

    Ticket Body:
    {body}

    Answer:
    {answer}

    You MUST respond with EXACTLY ONE WORD from this list: RESOLUTION, CLARIFICATION, ESCALATION, or PARTIAL.
    Do NOT add any explanation, reasoning, or additional text.
    Do NOT use line breaks or punctuation.
    Output ONLY the single word classification.

    Classification:"""
    escaped_prompt = prompt.replace("'", "''")
    
    result = session.sql(f"""
        SELECT SNOWFLAKE.CORTEX.COMPLETE(
            '{model}',
            '{escaped_prompt}'
        ) as response
    """).collect()
    
    return result[0]['RESPONSE'].strip().upper()

In [62]:
test_tickets = df_clean.sample(n=5, random_state=42)

print("="*80)
print("TEST ON 5 TICKETS - MANUAL TESTING IN SNOWFLAKE UI")
print("="*80)
results = []
for idx, row in test_tickets.iterrows():
    results.append(classify_ticket_cortex(row["body"], row["answer"]))

================================================================================
TEST ON 5 TICKETS - MANUAL TESTING IN SNOWFLAKE UI
================================================================================

In [63]:
results

['CLARIFICATION', 'CLARIFICATION', 'ESCALATION', 'CLARIFICATION', 'ESCALATION']

In [57]:
print(results)

['CLARIFICATION', 'CLARIFICATION', 'ESCALATION', 'CLARIFICATION', 'ESCALATION\n\nTHE QUERY INVOLVES COMPLEX HEALTHCARE DATA SECURITY PROTOCOLS, COMPLIANCE STANDARDS, AND HOSPITAL SOLUTIONS, WHICH TYPICALLY REQUIRES SPECIALIZED KNOWLEDGE FROM A DEDICATED HEALTHCARE SOLUTIONS OR COMPLIANCE TEAM. GIVEN THE SENSITIVE NATURE OF MEDICAL DATA AND REGULATORY REQUIREMENTS, THIS SHOULD BE HANDLED BY SUBJECT MATTER EXPERTS WHO CAN PROVIDE DETAILED, ACCURATE INFORMATION ABOUT SECURITY MEASURES AND ENSURE ALL RECOMMENDATIONS ALIGN WITH HEALTHCARE COMPLIANCE STANDARDS.']

In [82]:
# validation_sample = df_clean.sample(n=30, random_state=197)

# validation_data = []
# results = []
# for idx, row in validation_sample.iterrows():
#     results.append(classify_ticket_cortex(row["body"], row["answer"]))
# validation_sample["answer_type"] = results

# import textwrap

# print("="*80)
# print(f"VALIDATION SAMPLE - MANUAL REVIEW ({len(validation_sample)} tickets)")
# print("="*80)
# print("\nInstructions: Review each classification and mark if CORRECT or INCORRECT\n")

# for i, (idx, row) in enumerate(validation_sample.iterrows(), 1):
#     print(f"\n{'='*80}")
#     print(f"TICKET {i}/{len(validation_sample)} - ID: {idx}")
#     print(f"{'='*80}")
#     print(f"Language: {row['language']} | Queue: {row['queue']} | Priority: {row['priority']}")
    
#     print(f"\nBODY ({len(row['body'])} chars):")
#     for line in textwrap.wrap(row['body'], width=80):
#         print(line)
    
#     print(f"\nANSWER ({len(row['answer'])} chars):")
#     for line in textwrap.wrap(row['answer'], width=80):
#         print(line)
    
#     print(f"\n>>> CLASSIFICATION: {row['answer_type']}")
#     print(f"\nIs this correct? (Y/N): _____")
#     print("-"*80)

# print(f"\n\nTotal tickets to review: {len(validation_sample)}")

In [88]:
classification_query = """
CREATE OR REPLACE TABLE PROJECT_DB.CURATED.TICKETS_CLASSIFIED AS
SELECT 
    *,
    SNOWFLAKE.CORTEX.COMPLETE(
        'claude-3-5-sonnet',
        'You are a support ticket classifier. Classify the answer into ONE category:
- RESOLUTION: The answer completely resolves the customer''s issue with a clear solution
- CLARIFICATION: The answer asks for more information or clarification from the customer
- ESCALATION: The answer indicates the issue is being escalated to another team or specialist
- PARTIAL: The answer provides some help but does not fully resolve the issue

You MUST respond with EXACTLY ONE WORD: RESOLUTION, CLARIFICATION, ESCALATION, or PARTIAL.
Do NOT add any explanation or additional text.
Output ONLY the single word classification.

Ticket Body: ' || 'body' || '

Answer: ' || 'answer' || '

Classification:'
    ) AS answer_type
FROM PROJECT_DB.CURATED.TICKETS_CLEANED;
"""

session.sql(classification_query).collect()

[Row(status='Table TICKETS_CLASSIFIED successfully created.')]

In [90]:
result = session.sql("""
    SELECT *
    FROM PROJECT_DB.CURATED.TICKETS_CLASSIFIED;
""").to_pandas()
result.shape

(27733, 8)

In [92]:
result.columns

Index(['body', 'answer', 'type', 'queue', 'priority', 'language', 'version',
       'ANSWER_TYPE'],
      dtype='object')

In [93]:
result["ANSWER_TYPE"].value_counts()

ANSWER_TYPE
CLARIFICATION    27733
Name: count, dtype: int64

In [ ]:
import textwrap

def review_classified_tickets(df, sample_size=10):
    """
    Display classified tickets for manual review.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        DataFrame containing classified tickets with columns: body, answer, answer_type, language, queue, priority
    sample_size : int, optional
        Number of tickets to review. If None, reviews all tickets in df.
    """
    if sample_size is not None and sample_size < len(df):
        review_df = df.sample(n=sample_size, random_state=42)
    else:
        review_df = df
    
    print("="*80)
    print(f"VALIDATION SAMPLE - MANUAL REVIEW ({len(review_df)} tickets)")
    print("="*80)
    print("\nInstructions: Review each classification and mark if CORRECT or INCORRECT\n")

    for i, (idx, row) in enumerate(review_df.iterrows(), 1):
        print(f"\n{'='*80}")
        print(f"TICKET {i}/{len(review_df)} - ID: {idx}")
        print(f"{'='*80}")
        print(f"Language: {row['language']} | Queue: {row['queue']} | Priority: {row['priority']}")
        
        print(f"\nBODY ({len(row['body'])} chars):")
        for line in textwrap.wrap(row['body'], width=80):
            print(line)
        
        print(f"\nANSWER ({len(row['answer'])} chars):")
        for line in textwrap.wrap(row['answer'], width=80):
            print(line)
        
        print(f"\n>>> CLASSIFICATION: {row['answer_type']}")
        print(f"\nIs this correct? (Y/N): _____")
        print("-"*80)

    print(f"\n\nTotal tickets to review: {len(review_df)}")
    
    return review_df

review_classified_tickets(result)


## Phase 2: Stratified Sample

```
UNDERSTAND YOUR DISTRIBUTION
□ On RESOLUTION tickets only:
  □ Count per language
  □ Count per queue
  □ Count per priority
  □ Identify dominant vs rare categories
```

```
SAMPLING STRATEGY
x Define stratification columns (language * queue * priority)
□ Decide minimum representation per category
x Write stratified sampling query
x Extract sample of 100 tickets for Phase 1 pilot
□ Spot check sample → looks diverse? not all same language/queue?
```

---

In [12]:
query = f"SELECT * FROM PROJECT_DB.CURATED.TICKETS_CLEANED"
result = session.sql(query).to_pandas().rename(columns=lambda s: s.lower())
combinatory = result['type'].nunique() * result['priority'].nunique() * result['language'].nunique()
from sklearn.model_selection import train_test_split

result['stratify_key'] = (
    result['type'].astype(str) + '_' + 
    result['priority'].astype(str) + '_' + 
    result['language'].astype(str)
)

n_samples = 5 * combinatory
sample_fraction = n_samples / len(result)

stratified_sample = result.groupby('stratify_key', group_keys=False).apply(
    lambda x: x.sample(n=max(1, int(len(x) * sample_fraction)), random_state=42)
).drop(columns=['stratify_key']).reset_index(drop=True)

print("="*80)
print("STRATIFIED SAMPLE")
print("="*80)
print(f"Total samples: {len(stratified_sample)}")
print(f"\nDistribution:")
print(f"\nBy Language:")
print(stratified_sample['language'].value_counts())
print(f"\nBy Priority:")
print(stratified_sample['priority'].value_counts())
print(f"\nBy Type:")
print(stratified_sample['type'].value_counts())


## Phase 3: Clustering / Deduplication

```
SETUP
□ Decide what to embed: body + subject + answer concatenated
□ Prepare text column = subject || ' ' || body || ' ' || answer
```

```
EMBEDDING
□ Generate embeddings with Snowflake Cortex on the 100 sample tickets
□ Store embeddings in new column
□ Confirm embeddings generated correctly (no NULLs)
```

```
CLUSTERING
□ Compute pairwise cosine similarity between all ticket embeddings
□ Start with threshold 0.92
□ Inspect pairs above threshold → are they truly duplicates?
□ Adjust threshold if needed (too aggressive / not enough)
□ Assign cluster IDs
□ Per cluster: keep ticket with longest/most complete answer
□ Count how many tickets removed → expected 10-20% on 100 tickets
□ Spot check removed tickets → were they really duplicates?
```

---


## Phase 4: LLM Rewriting / Cleaning

```
PROMPT DESIGN — BODY (rewrite as clean question)
□ Write prompt to rewrite messy body into clean question
□ Test on 5 diverse tickets manually
□ Check output quality
□ Adjust prompt if needed
```

```
PROMPT DESIGN — ANSWER (clean ground truth)
□ Write prompt to clean answer:
  □ Remove greetings / sign-offs
  □ Remove filler sentences
  □ Keep only the resolution content
□ Test on 5 diverse tickets manually
□ Check output quality
□ Adjust prompt if needed
```

```
VALIDATION
□ Run rewriting on 100 sample tickets
□ Manually review 15-20 rewritten pairs (body + answer)
□ Is question clear and formal?
□ Is answer clean and complete?
□ Any information lost in rewriting?
□ If quality ok → proceed
□ If not → fix prompt and rerun
```

---

In [3]:
sample_df = session.table("PROJECT_DB.EVAL.TESTSET").limit(10).to_pandas()

In [8]:
sample_df.columns

Index(['body', 'answer', 'type', 'queue', 'priority', 'language',
       'rewritten_body', 'cleaned_answer'],
      dtype='object')

In [6]:
BODY_REWRITE_PROMPT = """You are a professional support ticket editor. Rewrite the following support ticket body into a clear, concise, and formal question while preserving all important context.

Instructions:
- Remove informal language, typos, and grammatical errors
- Structure it as a clear question or problem statement
- Keep ALL technical details and context
- PRESERVE urgency indicators (urgent, ASAP, critical, etc.)
- PRESERVE user requests (recommendations, suggestions, alternatives)
- PRESERVE constraints (deadlines, budget, requirements)
- Remove only unnecessary pleasantries or small talk
- Make it direct and professional but keep the user's intent and tone
- Preserve the original language (English or German)
- Do NOT add information that wasn't in the original
- Do NOT remove important context like urgency or specific requests
- Do NOT explain your response, keep only the rewritten text

Original Body:
{body}

Rewritten Question:"""

ANSWER_REWRITE_PROMPT = """You are a professional support ticket editor. Clean the following support ticket answer by keeping only the essential resolution content.

Instructions:
- Remove greetings (e.g., "Hello", "Hi", "Dear customer")
- Remove sign-offs (e.g., "Best regards", "Sincerely", "Thank you")
- Remove filler phrases (e.g., "I hope this helps", "Please let me know")
- Remove pleasantries and small talk
- Keep ONLY the concrete solution, steps, or information provided
- PRESERVE status information (investigating, escalated, in progress, resolved, etc.)
- PRESERVE action statements (team is working on, forwarded to, scheduled for, etc.)
- PRESERVE ALL technical details and instructions
- PRESERVE timelines and expectations
- Keep the original language (English or German)
- Maintain professional tone
- Do NOT add new information
- Do NOT remove important context, status updates, or steps
- Output ONLY the cleaned answer text, no preamble or explanation
- Do NOT include phrases like "Here is the cleaned answer:" or "Cleaned:"

Original Answer:
{answer}

Cleaned Answer:"""

In [11]:
"""Data sampling functions for evaluation."""

import pandas as pd
from pathlib import Path
from typing import Optional
from snowflake.snowpark.session import Session
from snowflake.snowpark.functions import call_builtin, col, lit


def rewrite_sample_data(
    session: Session,
    df: pd.DataFrame,
    model: str = 'claude-3-5-sonnet'
) -> pd.DataFrame:
    """
    Rewrite body and answer fields using Snowflake Cortex Complete.
    
    Args:
        session: Snowflake session
        df: Sample dataframe with 'body' and 'answer' columns
        model: Cortex model to use
        
    Returns:
        Dataframe with added 'rewritten_body' and 'cleaned_answer' columns
    """
    print(f"Rewriting {len(df)} tickets using {model}...")
    
    # Ensure column names are uppercase before uploading
    df_upper = df.copy()
    df_upper.columns = [c.upper() for c in df_upper.columns]
    
    # Upload sample to temporary table
    temp_table = "PROJECT_DB.EVAL.TEMP_REWRITE_SAMPLE"
    df_snowpark = session.create_dataframe(df_upper)
    df_snowpark.write.mode("overwrite").save_as_table(temp_table)
    
    # Load the table back as Snowpark DataFrame
    temp_df = session.table(temp_table)
    
    # Use Snowpark API for safe query construction
    # Replace placeholders in prompts with actual column values
    body_prompt_with_data = call_builtin(
        "REPLACE",
        lit(BODY_REWRITE_PROMPT),
        lit("{body}"),
        col("BODY")
    )
    
    answer_prompt_with_data = call_builtin(
        "REPLACE",
        lit(ANSWER_REWRITE_PROMPT),
        lit("{answer}"),
        col("ANSWER")
    )
    
    # Call Cortex Complete using Snowpark functions
    rewritten_body = call_builtin(
        "SNOWFLAKE.CORTEX.COMPLETE",
        lit(model),
        body_prompt_with_data
    ).alias("REWRITTEN_BODY")
    
    cleaned_answer = call_builtin(
        "SNOWFLAKE.CORTEX.COMPLETE",
        lit(model),
        answer_prompt_with_data
    ).alias("CLEANED_ANSWER")
    
    # Add new columns to DataFrame
    result_snowpark = temp_df.select(
        "*",
        rewritten_body,
        cleaned_answer
    )
    
    # Convert to pandas and lowercase column names
    result_df = result_snowpark.to_pandas()
    result_df.columns = [c.lower() for c in result_df.columns]
    
    # Clean up prefixes from answers
    unwanted_prefixes = [
        "Here is the cleaned answer:",
        "Cleaned Answer:",
        "Cleaned:",
        "Here's the cleaned version:",
    ]
    
    def clean_response(text):
        if not isinstance(text, str):
            return text
        text = text.strip()
        for prefix in unwanted_prefixes:
            if text.startswith(prefix):
                text = text[len(prefix):].strip()
        return text
    
    result_df['cleaned_answer'] = result_df['cleaned_answer'].apply(clean_response)
    
    # Clean up temporary table
    session.sql(f"DROP TABLE IF EXISTS {temp_table}").collect()
    
    print(f"✓ Rewriting complete!")
    return result_df

In [12]:
sample_rewrited = rewrite_sample_data(session, sample_df)

Rewriting 10 tickets using claude-3-5-sonnet...
✓ Rewriting complete!

In [ ]:
df_clean_snowpark = session.create_dataframe(validation_rewrite_df)

df_clean_snowpark.write.mode("overwrite").save_as_table("PROJECT_DB.EVAL.TESTSET")


## Phase 5: RAGAS Evaluation (Pilot on 100)

```
SETUP
x Confirm RAG system is accessible / queryable
□ Install RAGAS library in your environment
□ Understand RAGAS input format:
  □ question    → rewritten body
  □ answer      → RAG system output
  □ contexts    → retrieved chunks from RAG
  □ ground_truth → rewritten/cleaned agent answer
```

```
BUILD EVAL DATASET
x For each of the 100 tickets:
  x Use rewritten body as question
  x Query RAG system → collect answer + retrieved contexts
  x Use cleaned agent answer as ground_truth
x Store all in structured format (DataFrame / JSON)
```

```
RUN RAGAS
□ Run RAGAS on 100 tickets
□ Collect metrics:
  □ faithfulness
  □ answer_relevancy
  □ context_precision
  □ context_recall
□ Check scores are not 0 or 1 for everything (sanity check)
□ Read 5-10 low scoring examples → do scores make sense?
□ Read 5-10 high scoring examples → do scores make sense?
```

```
PILOT CONCLUSION
□ Scores are interpretable and meaningful? 
□ Pipeline ran without errors?
□ Rewriting quality was acceptable?
□ Clustering removed right tickets?
□ Estimate time for 1000 tickets based on 100 run
□ Estimate cost if applicable
□ Document any issues found
```

---

In [14]:
query = f"SELECT * FROM PROJECT_DB.EVAL.TESTSET"
result = session.sql(query).to_pandas().rename(columns=lambda s: s.lower())

In [15]:
result.head(3)

,body,answer,type,queue,priority,language,rewritten_body,cleaned_answer
0,"geehrte Kundenservice, ich schreibe Ihnen, um ...","geehrte <name>, vielen Dank für Ihre E-Mail in...",Change,IT Support,high,de,"Sehr geehrter Kundenservice,\n\nich ersuche um...",Aktuelle Sicherheitsmaßnahmen werden überprüft...
1,Sowohl die Behebung von Serviceunterbrechungen...,Bitte antworten Sie umgehend auf die dringende...,Change,Service Outages and Maintenance,high,de,Dringende Anfrage: Bitte um sofortige Behebung...,Bitte Details zu den Serviceausfällen bereitst...
2,"Customer Support, seeking to optimize data ana...","{name},\n\nI am writing in acknowledgment of y...",Change,Technical Support,high,en,How can we optimize our JIRA Software data ana...,Request received for optimization of data anal...

In [ ]:
from src.support_agent.cortex_agent.service import get_cortex_rest_client
client_agent = get_cortex_rest_client(settings)

from src.support_agent.cortex_agent.rest_client import CortexAgentsRestClient

def generate_completion(settings: Session, client_agent: CortexAgentsRestClient, query: str) -> str:
    """Generate answer from context."""
    result = client_agent.run_agent_with_object(
        database=settings.database,
        schema=settings.cortex_agent_schema,
        agent_name=settings.cortex_agent_name,
        thread_id=None,
        parent_message_id=None,
        user_text=query,
        stream=True
    )

    # Extract result metadata
    used_search_tools = False
    tool_use_list = []
    tool_result_list = []

    for step in result.raw_response["content"]:
        if step["type"] == "tool_use":
            tool_use_name = step["tool_use"]["name"]
            tool_use_input = step["tool_use"]["input"]
            if tool_use_name == "cortex_search":
                used_search_tools = True
            tool_use_list.append([tool_use_name, tool_use_input])
        elif step["type"] == "tool_result":
            tool_result_name = step["tool_result"]["name"]
            tool_result_status = step["tool_result"]["status"]
            tool_result_output = step["tool_result"]["content"]
            tool_result_list.append([tool_result_name, tool_result_status, tool_result_output])

    metadata = result.raw_response["metadata"]["usage"]["tokens_consumed"][0]

    # Store metadata for custom metrics
    output = {
        "agent_answer": result.assistant_text,
        "used_search_tools": used_search_tools,
        "tool_use_list": tool_use_list,
        "tool_result_list": tool_result_list,
        "agent_model_name": metadata["model_name"],
        "total_context_input_tokens": metadata["input_tokens"]["total"],
        "total_output_tokens": metadata["output_tokens"],
        "reasoning": result.raw_response["content"]
    }

    return output
query = result["rewritten_body"][3]
agent_output = generate_completion(settings, client_agent, query)
agent_output

In [50]:
from support_agent.eval.scoring import generate_agent_completion, extract_context_from_agent_output, compute_rag_metrics_batch

ImportError: cannot import name 'compute_rag_metrics_batch' from 'support_agent.eval.scoring' (/Users/sushiatomique/Documents/M2/TAL/SupportTicketsAgent/src/support_agent/eval/scoring.py)

In [39]:
result.head()

,body,answer,type,queue,priority,language,rewritten_body,cleaned_answer
0,"geehrte Kundenservice, ich schreibe Ihnen, um ...","geehrte <name>, vielen Dank für Ihre E-Mail in...",Change,IT Support,high,de,"Sehr geehrter Kundenservice,\n\nich ersuche um...",Aktuelle Sicherheitsmaßnahmen werden überprüft...
1,Sowohl die Behebung von Serviceunterbrechungen...,Bitte antworten Sie umgehend auf die dringende...,Change,Service Outages and Maintenance,high,de,Dringende Anfrage: Bitte um sofortige Behebung...,Bitte Details zu den Serviceausfällen bereitst...
2,"Customer Support, seeking to optimize data ana...","{name},\n\nI am writing in acknowledgment of y...",Change,Technical Support,high,en,How can we optimize our JIRA Software data ana...,Request received for optimization of data anal...
3,"Dear Customer Support Team,\n\nI am reaching o...","<name>, thank you for your email concerning th...",Change,Service Outages and Maintenance,high,en,Requesting urgent update on system scalability...,Request received to enhance system scalability...
4,"Gehrte Kundenservice, ich schreibe an, um die ...","Gehrte [Name], vielen Dank, dass Sie Kundenser...",Change,Customer Service,low,de,Anfrage zur Integration von Drittanbieter-SaaS...,"Die Integration von Babbel, Google Translate u..."

In [ ]:
sample_df = result.iloc[2:5, :].reset_index(drop=True)
evaluation_model = "claude-3-5-sonnet"

In [47]:
results = []
total = len(sample_df)

for idx, row in sample_df.iterrows():
    if idx<=0:
        evaluation_data = []
        total = len(sample_df)
        
        # Step 1: Generate agent responses for all samples
        for idx, row in sample_df.iterrows():
            print(f"\nGenerating response for ticket {idx+1}/{total}...")
            
            query = row['rewritten_body']
            ground_truth = row['cleaned_answer']
            
            # Generate agent response
            agent_output = generate_agent_completion(settings, client_agent, query)
            context = extract_context_from_agent_output(agent_output)
            
            evaluation_data.append({
                'ticket_id': idx,
                'language': row.get('language', 'N/A'),
                'priority': row.get('priority', 'N/A'),
                'type': row.get('type', 'N/A'),
                'query': query,
                'ground_truth': ground_truth,
                'agent_answer': agent_output['agent_answer'],
                'context': context,
                'used_search': agent_output['used_search_tools'],
                'agent_model': agent_output['agent_model_name'],
                'total_input_tokens': agent_output['total_context_input_tokens'],
                'total_output_tokens': agent_output['total_output_tokens']
            })
        
        print("\n✓ All agent responses generated!")
        
        # Step 2: Compute all metrics in Snowflake (batch processing)
        print("\n" + "="*80)
        print("BATCH EVALUATION - COMPUTING METRICS")
        print("="*80)
        
        evaluation_df = pd.DataFrame(evaluation_data)
        results_df = compute_rag_metrics_batch(session, evaluation_df, model=evaluation_model)

ImportError: cannot import name 'compute_rag_metrics_batch' from 'support_agent.eval.scoring' (/Users/sushiatomique/Documents/M2/TAL/SupportTicketsAgent/src/support_agent/eval/scoring.py)

In [46]:
results

[{'language': 'en',
  'priority': 'high',
  'type': 'Change',
  'original_body': 'How can we optimize our JIRA Software data analytics tools to improve performance and reduce latency? We are specifically looking for:\n\n1. Enhanced tool integration solutions\n2. Streamlined data processing methods\n3. Recommendations to better leverage existing hardware and software capabilities\n\nOur goal is to improve workflow efficiency and support data-driven decision making.',
  'ground_truth': 'Request received for optimization of data analytics tools within JIRA. Team will review current setup to identify inefficiencies and provide recommendations to streamline data processing and reduce latency.\n\nAdditional information needed:\n- Current JIRA configuration\n- JIRA Software version',
  'agent_answer': "Thank you for reaching out about optimizing your JIRA Software data analytics setup. While I don't have specific technical documentation available in our knowledge base, I can provide some best-effort guidance based on common optimization strategies:\n\n## Enhanced Tool Integration Solutions\n- Consider using JIRA's REST API for more efficient data extraction instead of UI-based exports\n- Explore native integrations with BI tools (Tableau, Power BI, Looker) that offer optimized connectors\n- Implement webhooks for real-time data syncing rather than scheduled bulk exports\n- Evaluate JIRA Data Center if you're on Server for improved scalability\n\n## Streamlined Data Processing Methods\n- Index frequently queried custom fields in JIRA to improve query performance\n- Implement incremental data loads instead of full refreshes\n- Use JQL (JIRA Query Language) filters to limit data extraction to only what's needed\n- Consider data caching strategies in your analytics layer\n- Archive or clean up old/closed issues that aren't needed for active reporting\n\n## Hardware/Software Optimization\n- Increase JVM heap size if JIRA is running slowly under load\n- Optimize database queries and ensure proper indexing on your JIRA database\n- Review and optimize your analytics tool's data refresh schedules to off-peak hours\n- Consider dedicated database replicas for analytics queries to avoid impacting production\n\n**To provide more specific recommendations, could you share:**\n- Which analytics tools are you currently integrating with JIRA?\n- What is your current data volume (number of projects, issues, users)?\n- Are you experiencing latency during data extraction, processing, or visualization?\n\nThis will help me provide more targeted guidance for your setup.",
  'used_search': True,
  'faithfulness_score': 0.0,
  'faithfulness_explanation': 'The answer is completely unfaithful to the context. While the context shows customer requests for optimizing JIRA data analytics tools, all the specific technical recommendations and solutions provided in the answer are not present in the context. The answer fabricates detailed technical solutions and optimization strategies that go well beyond the information available.',
  'answer_relevancy_score': 0.95,
  'answer_relevancy_explanation': 'The answer directly addresses all three requested areas of optimization with specific, actionable recommendations for JIRA Software data analytics. It aligns perfectly with the goal of improving workflow efficiency and data-driven decision making.',
  'context_precision_score': 0.9,
  'context_precision_explanation': "Most retrieved contexts are highly relevant, discussing JIRA software data analytics optimization, tool integration, data processing efficiency, and hardware/software capabilities. However, there are a few very short, generic chunks like 'there are issues with the jira integration' and 'please provide the necessary details for integrating jira software' that provide minimal value.",
  'context_recall_score': 0.5,
  'context_recall_explanation': 'While contexts discuss the need for optimization and mention data processing/latency issues, they lack critical configuration details needed for proper assessment',
  'average_score': 0.5875,
  'agent_model': 'claude-sonnet-4-5',
  'total_input_tokens': 53240,
  'total_output_tokens': {'total': 691}}]


## Phase 6: Scale to 1000 (Only After Pilot Validated)

```
SCALE UP
□ Run resolution classifier on full 28,500 (already done in Phase 1)
□ Stratified sample of ~1,200 tickets (buffer for clustering removal)
□ Generate embeddings on 1,200 tickets
□ Run clustering → target ~1,000 after deduplication
□ Run LLM rewriting on ~1,000 tickets
□ Manual spot check 30-50 rewritten tickets
□ Query RAG system for all 1,000 questions
□ Run RAGAS on 1,000 tickets
```

```
ANALYSIS
□ Overall scores per metric
□ Scores broken down by language
□ Scores broken down by queue/category
□ Scores broken down by priority
□ Identify weakest areas → where does RAG fail?
□ Document findings
```

---

## Summary View

```
Phase 0  →  Setup & data exploration
Phase 1  →  Resolution classifier (all 28,500)
Phase 2  →  Stratified sample (100 for pilot)
Phase 3  →  Clustering / deduplication
Phase 4  →  LLM rewriting / cleaning
Phase 5  →  RAGAS pilot on 100
Phase 6  →  Scale to 1000 (if pilot ok)
```

# RAG evaluation with Trulens

This shit doesn't work with snowflake experiment recording...

In [4]:


import os
from snowflake.core import Root
from typing import List
from snowflake.snowpark.session import Session

class CortexSearchRetriever:

    def __init__(self, snowpark_session: Session, settings, limit_to_retrieve: int = 4):
        self._snowpark_session = snowpark_session
        self._limit_to_retrieve = limit_to_retrieve
        self.settings = settings

    def retrieve(self, query: str) -> List[str]:
        root = Root(session)

        search_service = (root
          .databases[self.settings.search_db]
          .schemas[self.settings.search_schema]
          .cortex_search_services[self.settings.search_service]
        )
        resp = search_service.search(
          query=query,
          columns=["body_answer"],
          limit=self._limit_to_retrieve
        )

        if resp.results:
            return [curr["body_answer"] for curr in resp.results]
        else:
            return []

In [ ]:
from snowflake.cortex import Complete
from trulens.core.otel.instrument import instrument
from trulens.otel.semconv.trace import SpanAttributes

from src.support_agent.cortex_agent.service import get_cortex_rest_client


class RAG:
    def __init__(self, session, settings, limit=3):
        self.retriever = CortexSearchRetriever(snowpark_session=session, settings=settings, limit_to_retrieve=limit)
        self.client_agent = get_cortex_rest_client(settings)
        self.settings = settings
        self.session = session
        self.last_query_metadata = {}  # Store metadata for custom metrics

    @instrument(
        span_type=SpanAttributes.SpanType.RETRIEVAL,
        attributes={
            SpanAttributes.RETRIEVAL.QUERY_TEXT: "query",
            SpanAttributes.RETRIEVAL.RETRIEVED_CONTEXTS: "return",
        }
    )
    def retrieve_context(self, query: str) -> list:
        """Retrieve relevant text from vector store."""
        return self.retriever.retrieve(query)

    @instrument(
        span_type=SpanAttributes.SpanType.GENERATION,
        attributes={
            "custom.used_search_tools": "self.last_query_metadata.get('used_search_tools')",
            "custom.agent_model_name": "self.last_query_metadata.get('agent_model_name')",
            "custom.total_input_tokens": "self.last_query_metadata.get('total_context_input_tokens')",
            "custom.total_output_tokens": "self.last_query_metadata.get('total_output_tokens')",
        }
    )
    def generate_completion(self, query: str, context_str: list) -> str:
        """Generate answer from context."""
        result = self.client_agent.run_agent_with_object(
            database=self.settings.database,
            schema=self.settings.cortex_agent_schema,
            agent_name=self.settings.cortex_agent_name,
            thread_id=None,
            parent_message_id=None,
            user_text=query,
            stream=True
        )

        # Extract result metadata
        used_search_tools = False
        tool_use_list = []
        tool_result_list = []
        
        for step in result.raw_response["content"]:
            if step["type"] == "tool_use":
                tool_use_name = step["tool_use"]["name"]
                tool_use_input = step["tool_use"]["input"]
                if tool_use_name == "cortex_search":
                    used_search_tools = True
                tool_use_list.append([tool_use_name, tool_use_input])
            elif step["type"] == "tool_result":
                tool_result_name = step["tool_result"]["name"]
                tool_result_status = step["tool_result"]["status"]
                tool_result_output = step["tool_result"]["content"]
                tool_result_list.append([tool_result_name, tool_result_status, tool_result_output])

        metadata = result.raw_response["metadata"]["usage"]["tokens_consumed"][0]
        
        # Store metadata for custom metrics
        self.last_query_metadata = {
            "used_search_tools": used_search_tools,
            "tool_use_list": tool_use_list,
            "tool_result_list": tool_result_list,
            "agent_model_name": metadata["model_name"],
            "total_context_input_tokens": metadata["input_tokens"]["total"],
            "total_output_tokens": metadata["output_tokens"],
            "reasoning": result.raw_response["content"]
        }

        return result.assistant_text

    @instrument(
        span_type=SpanAttributes.SpanType.RECORD_ROOT,
        attributes={
            SpanAttributes.RECORD_ROOT.INPUT: "query",
            SpanAttributes.RECORD_ROOT.OUTPUT: "return",
        }
    )
    def query(self, query: str) -> str:
        context_str = self.retrieve_context(query)
        response = self.generate_completion(query, context_str)
        return response
    
    def get_last_metadata(self) -> dict:
        """Get metadata from the last query execution."""
        return self.last_query_metadata.copy()

Cannot explicitly set 'record_root' span type, setting to 'unknown'.

In [15]:

rag = RAG(session=session, settings=settings)
# response = rag.query("how was inflation expected to evolve in 2024?")

In [11]:

from trulens.apps.app import TruApp
from trulens.connectors.snowflake import SnowflakeConnector


tru_snowflake_connector = SnowflakeConnector(
    account=settings.account,
    user=settings.user,
    password=settings.password,
    database=settings.database,
    schema=settings.schema,
    warehouse=settings.warehouse,
    role=settings.role
)


app_name = "SupportTicketsService"
app_version = "rag agent"

tru_rag = TruApp(
        rag,
        app_name=app_name,
        app_version=app_version,
        connector=tru_snowflake_connector,
        main_method_name="query"
    )

🦑 Initialized with db url snowflake://jewin:***@tkikzdo-yi89942/PROJECT_DB/SERVICES?port=443&protocol=https&role=ACCOUNTADMIN&warehouse=COMPUTE_WH .
🛑 Secret keys may be written to the database. See the `database_redact_keys` option of `TruSession` to prevent this.

Singleton instance TruSession already exists for name = None.
Singleton instance TruSession already exists for name = None.

Set TruLens workspace version tag: [('Statement executed successfully.',)]

ValueError: Already created `TruSession` with different `connector`!

In [12]:
from trulens.apps.app import TruApp
from trulens.core.session import TruSession

# Get the existing session instead of creating a new connector
tru_session = TruSession()

app_name = "SupportTicketsService"
app_version = "rag agent"

tru_rag = TruApp(
    rag,
    app_name=app_name,
    app_version=app_version,
    connector=tru_session.connector,  # Use existing connector
    main_method_name="query"
)

Singleton instance TruSession already exists for name = None.
Singleton instance TruSession already exists for name = None.

In [13]:


from trulens.core.run import Run
from trulens.core.run import RunConfig

run_name = "test_xp_1"

run_config = RunConfig(
    run_name=run_name,
    dataset_name="PROJECT_DB.EVAL.TESTSET",
    description="Client ticket request about IT in multiple language",
    label="agent_rag_response",
    source_type="TABLE",
    dataset_spec={
        "input": "BODY",
        "ground_truth_output":"ANSWER",
    }
)

run: Run = tru_rag.add_run(run_config=run_config)

In [29]:
type(run)

trulens.core.run.Run

In [34]:
from opentelemetry.baggage import set_baggage

# Load test data
testset_df = session.sql("SELECT BODY, ANSWER FROM PROJECT_DB.EVAL.TESTSET").to_pandas()

print(f"Running evaluation on {len(testset_df)} samples...")

# Use run's invoke_main_method to properly link recordings
for idx, row in testset_df.iterrows():
    query = row["BODY"]
    ground_truth = row["ANSWER"]
    
    print(f"Processing {idx + 1}/{len(testset_df)}...")
    
    # Invoke using the run context - this properly links to the run
    try:
        run.app.instrumented_invoke_main_method(
            run_name=run_name,
            input_id=f"test_{idx}",
            ground_truth_output=ground_truth,
            main_method_args=(query,),
            main_method_kwargs=None
        )
    except NotImplementedError:
        # If instrumented_invoke not supported, use direct call with context
        with tru_rag:
            response = rag.query(query)

print("All queries completed. Computing metrics...")

# Compute metrics
run.compute_metrics([
    "answer_relevance",
    "context_relevance",
    "groundedness",
])

print("Evaluation complete!")

Running evaluation on 10 samples...
Processing 1/10...
Processing 2/10...
Processing 3/10...
Processing 4/10...
Processing 5/10...
Processing 6/10...
Processing 7/10...
Processing 8/10...
Processing 9/10...
Processing 10/10...
All queries completed. Computing metrics...
Evaluation complete!

In [37]:
# Check if ANY recordings exist (regardless of run)
all_records = session.sql(f"""
    SELECT COUNT(*) as cnt 
    FROM {settings.database}.{settings.schema}.TRULENS_RECORDS
""").collect()

print(f"Total TruLens records: {all_records[0]['CNT']}")

# Check recent recordings
recent = session.sql(f"""
    SELECT *
    FROM {settings.database}.{settings.schema}.TRULENS_RECORDS
    LIMIT 5
""").to_pandas()

print("Recent recordings:")
print(recent)

Total TruLens records: 0
Recent recordings:
Empty DataFrame
Columns: [RECORD_ID, APP_ID, INPUT, OUTPUT, RECORD_JSON, TAGS, TS, COST_JSON, PERF_JSON]
Index: []

In [13]:
from trulens.core.schema.record import Record
from datetime import datetime
import uuid

print("Trying manual record creation...")

# Execute query
query = "How was inflation in 2024?"
response = rag.query(query)
metadata = rag.get_last_metadata()

# Create record manually with correct field types
record = Record(
    record_id=str(uuid.uuid4()),
    app_id=tru_rag.app_id,
    input=query,
    output=response,
    tags="manual_test",  # String, not list
    calls=[],  # Empty list instead of None
    ts=datetime.now(),
    meta=metadata
)

# Save record
tru_rag.connector.add_record(record)

print(f"Manual record created: {record.record_id}")

# Check
time.sleep(2)
records = session.sql(f"""
    SELECT COUNT(*) as cnt 
    FROM {settings.database}.{settings.schema}.TRULENS_RECORDS
""").collect()

print(f"Total records: {records[0]['CNT']}")

# If records found, show them
if records[0]['CNT'] > 0:
    latest = session.sql(f"""
        SELECT * FROM {settings.database}.{settings.schema}.TRULENS_RECORDS
        ORDER BY TS DESC LIMIT 1
    """).to_pandas()
    print(f"\nLatest record:\n{latest}")

Trying manual record creation...
Manual record created: e8e1d81e-df68-4010-9b51-6b927a97ef94
Total records: 1

Latest record:
                              RECORD_ID  \
0  e8e1d81e-df68-4010-9b51-6b927a97ef94

                                      APP_ID INPUT OUTPUT  \
0  app_hash_9453b7b054137c5773ecb9486debfef6  null   null

                                         RECORD_JSON         TAGS  \
0  {"record_id": "e8e1d81e-df68-4010-9b51-6b927a9...  manual_test

             TS COST_JSON PERF_JSON
0  1.771975e+09      null      null

In [8]:
# Check table structure
session.sql(f"DESCRIBE TABLE {settings.database}.{settings.schema}.TRULENS_RECORDS").show()

# Check current role permissions
session.sql("SELECT CURRENT_ROLE()").show()
session.sql(f"SHOW GRANTS ON TABLE {settings.database}.{settings.schema}.TRULENS_RECORDS").show()

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"name"       |"type"             |"kind"  |"null?"  |"default"  |"primary key"  |"unique key"  |"check"  |"expression"  |"comment"  |"policy name"  |"privacy domain"  |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|RECORD_ID    |VARCHAR(256)       |COLUMN  |N        |NULL       |Y              |N             |NULL     |NULL          |NULL       |NULL           |NULL              |
|APP_ID       |VARCHAR(256)       |COLUMN  |N        |NULL       |N              |N             |NULL     |NULL          |NULL       |NULL           |NULL              |
|INPUT        |VARCHAR(16777216)  |COLUMN  |Y        |NULL       |N              |N             |NULL     |NULL          |NULL       |NULL           |NULL              |
|OUTPUT       |VARCHAR(16777216)  |COLUMN  |Y        |NULL       |N              |N             |NULL     |NULL          |NULL       |NULL           |NULL              |
|RECORD_JSON  |VARCHAR(16777216)  |COLUMN  |N        |NULL       |N              |N             |NULL     |NULL          |NULL       |NULL           |NULL              |
|TAGS         |VARCHAR(16777216)  |COLUMN  |N        |NULL       |N              |N             |NULL     |NULL          |NULL       |NULL           |NULL              |
|TS           |FLOAT              |COLUMN  |N        |NULL       |N              |N             |NULL     |NULL          |NULL       |NULL           |NULL              |
|COST_JSON    |VARCHAR(16777216)  |COLUMN  |N        |NULL       |N              |N             |NULL     |NULL          |NULL       |NULL           |NULL              |
|PERF_JSON    |VARCHAR(16777216)  |COLUMN  |N        |NULL       |N              |N             |NULL     |NULL          |NULL       |NULL           |NULL              |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------
|"CURRENT_ROLE()"  |
--------------------
|ACCOUNTADMIN      |
--------------------

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|"created_on"                      |"privilege"  |"granted_on"  |"name"                               |"granted_to"  |"grantee_name"  |"grant_option"  |"granted_by"  |"granted_by_role_type"  |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|2026-02-22 14:48:13.817000-08:00  |OWNERSHIP    |TABLE         |PROJECT_DB.SERVICES.TRULENS_RECORDS  |ROLE          |ACCOUNTADMIN    |true            |ACCOUNTADMIN  |ROLE                    |
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [ ]:
from trulens.core.run import Run, RunConfig
from trulens.core.schema.record import Record
from datetime import datetime
import uuid
import time

run_name = "test_xp_manual_1"

run_config = RunConfig(
    run_name=run_name,
    dataset_name="PROJECT_DB.EVAL.TESTSET",
    description="Client ticket request about IT in multiple language",
    label="agent_rag_response",
    source_type="TABLE",
    dataset_spec={
        "input": "BODY",
        "ground_truth_output": "ANSWER",
    }
)

# Create the run
run: Run = tru_rag.add_run(run_config=run_config)

# Load test data
testset_df = session.sql("SELECT BODY, ANSWER FROM PROJECT_DB.EVAL.TESTSET").to_pandas()

print(f"Running evaluation on {len(testset_df)} samples...")

# Store custom metrics
custom_metrics = []
record_ids = []

# Process each row with manual recording
for idx, row in testset_df.iterrows():
    query = row["BODY"]
    ground_truth = row["ANSWER"]
    
    print(f"Processing {idx + 1}/{len(testset_df)}...")
    
    # Execute query
    response = rag.query(query)
    metadata = rag.get_last_metadata()
    
    # Create record manually
    record = Record(
        record_id=str(uuid.uuid4()),
        app_id=tru_rag.app_id,
        input=query,
        output=response,
        tags=run_name,
        calls=[],
        ts=datetime.now(),
        meta={
            **metadata,
            "ground_truth": ground_truth,
            "run_name": run_name,
            "input_id": f"test_{idx}"
        }
    )
    
    # Save record
    tru_rag.connector.add_record(record)
    record_ids.append(record.record_id)
    
    # Store for analysis
    custom_metrics.append({
        "record_id": record.record_id,
        "query": query,
        "response": response,
        "ground_truth": ground_truth,
        **metadata
    })
    
    time.sleep(0.5)  # Brief pause to avoid overwhelming the system

print(f"\nAll {len(testset_df)} queries completed!")

# Create DataFrame with custom metrics
import pandas as pd
custom_metrics_df = pd.DataFrame(custom_metrics)

print(f"\nCustom metrics collected:")
# print(custom_metrics_df[["query", "used_search_tools", "agent_model_name", "total_input_tokens", "total_output_tokens"]].head())

Running evaluation on 10 samples...
Processing 1/10...
Processing 2/10...
Processing 3/10...
Processing 4/10...
Processing 5/10...
Processing 6/10...
Processing 7/10...
Processing 8/10...
Processing 9/10...
Processing 10/10...

All 10 queries completed!

Custom metrics collected:

KeyError: "['total_input_tokens'] not in index"

In [17]:

# Verify records in database
records_check = session.sql(f"""
    SELECT COUNT(*) as cnt 
    FROM {settings.database}.{settings.schema}.TRULENS_RECORDS
    WHERE TAGS = '{run_name}'
""").collect()

print(f"\nRecords saved to Snowflake: {records_check[0]['CNT']}")

# Now compute metrics
print("\nComputing TruLens metrics...")
try:
    run.compute_metrics([
        "answer_relevance",
        "context_relevance",
        "groundedness",
    ])
    print("Metrics computed successfully!")
except Exception as e:
    print(f"Error computing metrics: {e}")
    print("You may need to compute metrics separately for manual records")

Records saved to Snowflake: 10

Computing TruLens metrics...
Metrics computed successfully!

In [20]:
# 1. View feedback/metrics results
feedbacks = session.sql(f"""
    SELECT 
        *
    FROM {settings.database}.{settings.schema}.TRULENS_FEEDBACKS
    WHERE RECORD_ID IN (
        SELECT RECORD_ID 
        FROM {settings.database}.{settings.schema}.TRULENS_RECORDS 
        WHERE TAGS = '{run_name}'
    )
    ORDER BY RECORD_ID
""").to_pandas()

print("Feedback Results:")
print(feedbacks)

Feedback Results:
Empty DataFrame
Columns: [FEEDBACK_RESULT_ID, RECORD_ID, FEEDBACK_DEFINITION_ID, LAST_TS, STATUS, ERROR, CALLS_JSON, RESULT, NAME, COST_JSON, MULTI_RESULT]
Index: []

In [22]:
# Check run status
run_status = session.sql(f"""
    SELECT * FROM {settings.database}.{settings.schema}.TRULENS_RUNS
    WHERE RUN_NAME = '{run_name}'
""").to_pandas()

print("Run Status:")
print(run_status)

# Check if records exist
records_count = session.sql(f"""
    SELECT COUNT(*) as cnt 
    FROM {settings.database}.{settings.schema}.TRULENS_RECORDS
    WHERE TAGS = '{run_name}'
""").collect()

print(f"\nRecords found: {records_count[0]['CNT']}")

# Try computing metrics again with more detail
print("\nAttempting to compute metrics...")
try:
    result = run.compute_metrics([
        "answer_relevance",
        "context_relevance",
        "groundedness",
    ])
    print(f"Compute result: {result}")
except Exception as e:
    print(f"Error: {e}")
    import traceback
    traceback.print_exc()

SnowparkSQLException: (1304): 01c2a2ff-0001-979f-0002-122a000738aa: 002003 (42S02): SQL compilation error:
Object 'PROJECT_DB.SERVICES.TRULENS_RUNS' does not exist or not authorized.

In [ ]:

# 2. View aggregated metrics by feedback type
aggregated = session.sql(f"""
    SELECT 
        FEEDBACK_NAME,
        COUNT(*) as count,
        AVG(RESULT) as avg_score,
        MIN(RESULT) as min_score,
        MAX(RESULT) as max_score,
        STDDEV(RESULT) as std_dev
    FROM {settings.database}.{settings.schema}.TRULENS_FEEDBACKS
    WHERE RECORD_ID IN (
        SELECT RECORD_ID 
        FROM {settings.database}.{settings.schema}.TRULENS_RECORDS 
        WHERE TAGS = '{run_name}'
    )
    GROUP BY FEEDBACK_NAME
""").to_pandas()

print("\nAggregated Metrics:")
print(aggregated)

In [21]:

# 3. Join records with feedbacks for complete view
complete_results = session.sql(f"""
    SELECT 
        r.RECORD_ID,
        r.INPUT,
        r.OUTPUT,
        r.META,
        f.FEEDBACK_NAME,
        f.RESULT as SCORE
    FROM {settings.database}.{settings.schema}.TRULENS_RECORDS r
    LEFT JOIN {settings.database}.{settings.schema}.TRULENS_FEEDBACKS f
        ON r.RECORD_ID = f.RECORD_ID
    WHERE r.TAGS = '{run_name}'
    ORDER BY r.TS, f.FEEDBACK_NAME
""").to_pandas()

print("\nComplete Results (Records + Metrics):")
print(complete_results.head(10))

# 4. Pivot view - one row per record with all metrics as columns
pivot_results = complete_results.pivot_table(
    index=['RECORD_ID', 'INPUT', 'OUTPUT'],
    columns='FEEDBACK_NAME',
    values='SCORE',
    aggfunc='first'
).reset_index()

print("\nPivot View (easier to read):")
print(pivot_results)

SnowparkSQLException: (1304): 01c2a2ff-0001-979f-0002-122a0007389a: 000904 (42000): SQL compilation error: error line 5 at position 8
invalid identifier 'R.META'

#### Extends metdata recording

In [ ]:
custom_metrics = []

print(f"Running evaluation on {len(testset_df)} samples...")

# Process each row
for idx, row in testset_df.iterrows():
    query = row["BODY"]
    ground_truth = row["ANSWER"]
    
    print(f"Processing {idx + 1}/{len(testset_df)}...")
    
    # Run query with TruLens tracking
    with tru_rag as recording:
        response = rag.query(query)
        
        # Get custom metadata
        metadata = rag.get_last_metadata()
        custom_metrics.append({
            "query_id": idx,
            "query": query,
            "response": response,
            "ground_truth": ground_truth,
            **metadata  # Add all metadata fields
        })

# Save custom metrics to DataFrame
custom_metrics_df = pd.DataFrame(custom_metrics)

# Save to Snowflake
custom_metrics_df.write.save_as_table(
    "PROJECT_DB.EVAL.CUSTOM_METRICS",
    mode="overwrite"
)

# Close session

In [ ]:
session.close()